[package]
authors.workspace = true
edition.workspace = true
name = "autorole"
publish.workspace = true
version.workspace = true

[features]

[dependencies]
common = { path = "../common" }
poise = { workspace = true }
