[package]
name = "autorole"
version = "0.1.0"
edition = "2021"
publish = false

[features]

[dependencies]
common = { path = "../common" }
db = { path = "../db" }
poise = { workspace = true }
sea-orm = { workspace = true }
