[package]
authors.workspace = true
edition.workspace = true
name = "johnny"
publish.workspace = true
version.workspace = true

[features]

[dependencies]
common = { path = "../common" }
imgurs = "0.11.2"
poise = { workspace = true }
rand = "0.8.5"
serde = { workspace = true }
