[package]
name = "johnny"
version = "0.1.0"
edition = "2021"

[features]
default = ["tui"]

# general
tui = ["dep:ratatui", "dep:crossterm", "dep:ansi-to-tui", "dep:once_cell"]
johnny = ["dep:imgurs", "dep:once_cell"]
verbose = []

# modules
autorole = []

[dependencies]
ansi-to-tui = { version = "3.1.0", optional = true }
chrono = "0.4.26"
crossterm = { version = "0.26.1", optional = true }
dotenvy_macro = "0.15.7"
imgurs = { version = "0.11.2", optional = true }
once_cell = { version = "1.18.0", optional = true }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
poise = "0.5.5"
rand = "0.8.5"
ratatui = { version = "0.21.0", optional = true }
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
tokio = { version = "1.28.2", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
