[package]
name = "johnny"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[workspace]
members = [".", "entity", "migration"]

[features]
default = ["tui"]

# general
tui = ["dep:ratatui", "dep:crossterm", "dep:ansi-to-tui"]
johnny = ["dep:imgurs", "verbose", "sqlite"]
verbose = []

# database drivers
postgres = ["dep:sea-orm", "sea-orm?/sqlx-postgres", "dep:entity", "dep:migration"]
mysql = ["dep:sea-orm", "sea-orm?/sqlx-mysql", "dep:entity", "dep:migration"]
sqlite = ["dep:sea-orm", "sea-orm?/sqlx-sqlite", "dep:entity", "dep:migration"]

# modules
autorole = [] # needs database driver

[dependencies]
entity = { path = "entity", optional = true }
migration = { path = "migration", optional = true }
ansi-to-tui = { version = "3.1.0", optional = true }
chrono = "0.4.26"
crossterm = { version = "0.26.1", optional = true }
dotenvy_macro = "0.15.7"
imgurs = { version = "0.11.2", optional = true }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
poise = "0.5.5"
rand = "0.8.5"
ratatui = { version = "0.21.0", optional = true }
sea-orm = { version = "0.11.3", optional = true, features = ["runtime-tokio-rustls", "macros"] }
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
tokio = { version = "1.28.2", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[build-dependencies]
migration = { path = "migration" }
sea-orm-codegen = "0.11.3"
