[package]
name = "johnny"
version = "0.1.0"
edition = "2021"

[features]
johnny = []
verbose = []

[dependencies]
chrono = "0.4.26"
crossterm = "0.26.1"
debug-ignore = "1.0.5"
dotenvy_macro = "0.15.7"
imgurs = "0.11.2"
poise = "0.5.5"
rand = "0.8.5"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
tokio = { version = "1.28.2", features = ["full"] }
tui = "0.19.0"
