[package]
name = "johnny"
version = "0.1.0"
edition = "2021"

[features]
default = ["tui"]
tui = ["dep:tui", "dep:crossterm"]
johnny = ["dep:imgurs"]
verbose = []

[dependencies]
chrono = "0.4.26"
crossterm = { version = "0.26.1", optional = true }
dotenvy_macro = "0.15.7"
imgurs = { version = "0.11.2", optional = true }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
poise = "0.5.5"
rand = "0.8.5"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
tokio = { version = "1.28.2", features = ["full"] }
tui = { version = "0.19.0", optional = true }
