[package]
authors.workspace = true
edition.workspace = true
name = "sticky"
publish.workspace = true
version.workspace = true

[features]

[dependencies]
common = { path = "../common", features = ["sticky"] }
poise = { workspace = true }
