[package]
authors.workspace = true
edition.workspace = true
name = "tui"
publish.workspace = true
version.workspace = true

[features]

[dependencies]
common = { path = "../common", features = ["tui"] }
crossterm = { workspace = true }
logger = { path = "../logger", features = ["tui"] }
ratatui = { workspace = true }
