[package]
name = "bot"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[features]
johnny = ["dep:johnny", "common/johnny", "sqlite", "verbose", "tui", "autorole", "pride"]
dev = ["dep:dotenvy_macro"]
tui = ["dep:tui", "logger/tui"]
verbose = ["logger/verbose"]

# moderation
moderation = ["autorole"]
autorole = ["dep:autorole", "db?/autorole"]

# image
image = ["pride"]
pride = ["dep:pride"]

# db
db = ["dep:db", "dep:migration", "dep:sea-orm", "common/db"]
postgres = ["db", "sea-orm?/sqlx-postgres"]
mysql = ["db", "sea-orm?/sqlx-mysql"]
sqlite = ["db", "sea-orm?/sqlx-sqlite"]

[dependencies]
autorole = { path = "../autorole", optional = true }
color-eyre = { workspace = true }
common = { path = "../common" }
db = { path = "../db", optional = true }
dotenvy_macro = { version = "0.15.7", optional = true }
johnny = { path = "../johnny", optional = true }
logger = { path = "../logger" }
migration = { path = "../../migration", optional = true }
poise = { workspace = true }
pride = { path = "../pride", optional = true }
sea-orm = { workspace = true, optional = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = "0.7.6"
tui = { path = "../tui", optional = true }

[build-dependencies]
cfg_aliases = { workspace = true }
