[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "bot"
publish.workspace = true
version.workspace = true

[features]
dev = []
johnny = [
  "dep:johnny",
  "common/johnny",
  "sqlite",
  "verbose",
  "autorole",
  "pride",
]
tui = ["dep:tui", "logger/tui"]
verbose = ["logger/verbose"]

# moderation
autorole = ["dep:autorole", "db?/autorole"]
moderation = ["autorole"]

# image
image = ["pride"]
pride = ["dep:pride"]

# db
db = ["dep:db", "dep:migration", "dep:sea-orm", "common/db"]
mysql = ["db", "sea-orm?/sqlx-mysql"]
postgres = ["db", "sea-orm?/sqlx-postgres"]
sqlite = ["db", "sea-orm?/sqlx-sqlite"]

[dependencies]
autorole = { path = "../autorole", optional = true }
color-eyre = { workspace = true }
common = { path = "../common" }
db = { path = "../db", optional = true }
johnny = { path = "../johnny", optional = true }
logger = { path = "../logger" }
migration = { path = "../../migration", optional = true }
poise = { workspace = true }
pride = { path = "../pride", optional = true }
sea-orm = { workspace = true, optional = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = "0.7.6"
tui = { path = "../tui", optional = true }

[build-dependencies]
cfg_aliases = { workspace = true }
rayon = { workspace = true }
