[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "bot"
publish.workspace = true
version.workspace = true

[features]
johnny = ["dep:johnny", "common/johnny", "sqlite", "verbose", "autorole", "pride", "sticky"]
tui = ["dep:tui", "logger/tui"]
verbose = ["logger/verbose"]

# moderation
autorole = ["dep:autorole", "common/autorole"]
moderation = ["autorole", "sticky"]
sticky = ["dep:sticky", "common/sticky"]

# image
image = ["pride"]
pride = ["dep:pride"]

# db
db = ["common/db-events", "dep:sqlx"]
mysql = ["db", "common/mysql"]
postgres = ["db", "common/postgres"]
sqlite = ["db", "common/sqlite"]

[dependencies]
autorole = { path = "../autorole", optional = true }
color-eyre = { workspace = true }
common = { path = "../common" }
johnny = { path = "../johnny", optional = true }
logger = { path = "../logger" }
poise = { workspace = true }
pride = { path = "../pride", optional = true }
serde = { workspace = true }
sqlx = { workspace = true, optional = true }
sticky = { path = "../sticky", optional = true }
tokio = { workspace = true }
toml = "0.7.6"
tui = { path = "../tui", optional = true }

[build-dependencies]
cfg_aliases = { workspace = true }
rayon = { workspace = true }
