[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "common"
publish.workspace = true
version.workspace = true

[features]
johnny = []
tui = ["dep:ratatui", "dep:crossterm"]

autorole = ["dep:once_cell", "dep:rustflake"]
sticky = ["dep:once_cell", "dep:rustflake"]

db = [
  "dep:sqlx",
  "dep:sea-query",
  "dep:sea-query-binder",
  "dep:refinery",
  "dep:barrel",
  "dep:entity",
  "dep:paste",
]
db-events = []

mysql = [
  "db",
  "sea-query/backend-mysql",
  "sea-query-binder/sqlx-mysql",
  "sqlx/mysql",
  "refinery/mysql",
  "barrel/mysql",
]
postgres = [
  "db",
  "sea-query/backend-postgres",
  "sea-query-binder/sqlx-postgres",
  "sqlx/postgres",
  "refinery/postgres",
  "barrel/pg",
]
sqlite = [
  "db",
  "sea-query/backend-sqlite",
  "sea-query-binder/sqlx-sqlite",
  "sqlx/sqlite",
  "refinery/rusqlite",
  "barrel/sqlite3",
]

[dependencies]
barrel = { version = "0.7.0", optional = true }
cfg-if = "1.0.0"
color-eyre = { workspace = true }
crossterm = { workspace = true, optional = true }
entity = { path = "entity", optional = true }
once_cell = { workspace = true, optional = true }
paste = { version = "1.0.14", optional = true }
poise = { workspace = true }
ratatui = { workspace = true, optional = true }
rayon = { workspace = true }
refinery = { version = "0.8.10", optional = true }
rustflake = { version = "0.1.1", optional = true }
sea-query = { workspace = true, optional = true }
sea-query-binder = { workspace = true, optional = true }
serenity = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, optional = true }

[build-dependencies]
cfg_aliases = { workspace = true }
