[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "common"
publish.workspace = true
version.workspace = true

[features]
db = []
johnny = []
tui = ["dep:ratatui", "dep:crossterm"]

[dependencies]
cfg-if = "1.0.0"
color-eyre = { workspace = true }
crossterm = { workspace = true, optional = true }
poise = { workspace = true }
ratatui = { workspace = true, optional = true }
rayon = { workspace = true }
sea-orm = { workspace = true }
serenity = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
