[package]
authors.workspace = true
edition.workspace = true
name = "entity"
publish.workspace = true
version.workspace = true

[lib]
proc-macro = true

[features]

[dependencies]
heck = { version = "0.4", default-features = false }
quote = { version = "1", default-features = false }
syn = { version = "1", default-features = false }
