[package]
authors.workspace = true
edition.workspace = true
name = "pride"
publish.workspace = true
version.workspace = true

[features]

[dependencies]
common = { path = "../common" }
image = { workspace = true }
poise = { workspace = true }
pride-overlay = "1.1.0"
reqwest = { workspace = true }
strum = { workspace = true }
