[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "db"
publish.workspace = true
version.workspace = true

[features]
autorole = []

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.72"
common = { path = "../common" }
migration = { path = "../../migration" }
once_cell = "1.18.0"
poise = { workspace = true }
rustflake = "0.1.1"
sea-orm = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
migration = { path = "../../migration" }
rust-format = "0.3.4"
sea-orm-codegen = "0.11.3"
