[package]
authors.workspace = true
build = "build.rs"
edition.workspace = true
name = "db"
publish.workspace = true
version.workspace = true

[features]
autorole = ["dep:once_cell", "dep:rustflake"]
sticky = ["dep:once_cell", "dep:rustflake"]

events = []

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.72"
common = { path = "../common" }
migration = { path = "../../migration" }
once_cell = { workspace = true, optional = true }
poise = { workspace = true }
rustflake = { version = "0.1.1", optional = true }
sea-orm = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
migration = { path = "../../migration" }
rust-format = "0.3.4"
sea-orm-codegen = "0.11.3"
