name: Clippy
permissions: write-all

on:
  push:
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set-up mold
        uses: rui314/setup-mold@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Set-up Rust caching
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features johnny,verbose,sqlite,moderation,image,tui
